import type { Handler, HandlerEvent } from '@netlify/functions'
import { v4 as uuidv4 } from 'uuid'

// Import from the lib path to avoid pdf-parse's test-file-loading side-effect
// eslint-disable-next-line @typescript-eslint/no-require-imports
const pdfParse = require('pdf-parse/lib/pdf-parse') as (
  buffer: Buffer,
) => Promise<{ text: string }>

// ── Types (mirror frontend/src/types/index.ts) ────────────────────────────────

interface PdfPosition {
  page: number
  y: number
  height: number
}

interface ContactAuthority {
  paymentRequests: boolean
  callbacks: boolean
  communicationsAndNotices: boolean
}

interface Contact {
  id: string
  action: string
  fullLegalName: string
  primaryPhone: string
  email: string
  corporateTitle: string
  alternatePhone: string
  countryOfResidence: string
  authorities: ContactAuthority
  pdfPosition?: PdfPosition
}

interface ContactGroup {
  id: string
  formType: string
  contacts: Contact[]
}

interface ParsedDocument {
  fileName: string
  groups: ContactGroup[]
}

// ── Parser ────────────────────────────────────────────────────────────────────

const VALID_ACTIONS = new Set(['Add', 'Edit', 'Delete', 'No Change'])

const START_MARKER = '===CONTACT_DATA_BEGIN==='
const END_MARKER = '===CONTACT_DATA_END==='

/** Exported for unit tests */
export function parseSection(text: string, fileName: string): ParsedDocument {
  const si = text.indexOf(START_MARKER)
  const ei = text.indexOf(END_MARKER)

  if (si === -1 || ei === -1) {
    throw new Error(
      'No machine-readable contact data found. ' +
        'Please upload a Banking Contact Authorization PDF generated by this system.',
    )
  }

  const lines = text
    .slice(si + START_MARKER.length, ei)
    .trim()
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)

  const groups: ContactGroup[] = []
  let currentGroup: ContactGroup | null = null

  for (const line of lines) {
    if (line.startsWith('group:')) {
      currentGroup = { id: uuidv4(), formType: line.slice(6).trim(), contacts: [] }
      groups.push(currentGroup)
    } else if (line.startsWith('contact:') && currentGroup) {
      const [
        action = 'No Change',
        fullLegalName = '',
        primaryPhone = '',
        email = '',
        corporateTitle = '',
        alternatePhone = '',
        countryOfResidence = '',
        pr = 'false',
        cb = 'false',
        cn = 'false',
        page = '1',
        y = '0',
        h = '30',
      ] = line.slice(8).split('|')

      const pdfY = parseFloat(y)
      const pdfH = parseFloat(h)
      const pdfPage = parseInt(page, 10)

      currentGroup.contacts.push({
        id: uuidv4(),
        action: VALID_ACTIONS.has(action) ? action : 'No Change',
        fullLegalName,
        primaryPhone,
        email,
        corporateTitle,
        alternatePhone,
        countryOfResidence,
        authorities: {
          paymentRequests: pr === 'true',
          callbacks: cb === 'true',
          communicationsAndNotices: cn === 'true',
        },
        // Only attach position when valid coordinates are present
        pdfPosition: pdfY > 0 ? { page: pdfPage, y: pdfY, height: pdfH } : undefined,
      })
    }
  }

  return { fileName, groups }
}

// ── Handler ───────────────────────────────────────────────────────────────────

const CORS_HEADERS = {
  'Content-Type': 'application/json',
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'Content-Type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
}

export const handler: Handler = async (event: HandlerEvent) => {
  if (event.httpMethod === 'OPTIONS') {
    return { statusCode: 204, headers: CORS_HEADERS, body: '' }
  }

  if (event.httpMethod !== 'POST') {
    return {
      statusCode: 405,
      headers: CORS_HEADERS,
      body: JSON.stringify({ error: 'Method not allowed' }),
    }
  }

  try {
    const body = JSON.parse(event.body ?? '{}') as {
      fileName?: string
      fileData?: string
    }

    if (!body.fileData) {
      return {
        statusCode: 400,
        headers: CORS_HEADERS,
        body: JSON.stringify({ error: 'Missing fileData (base64-encoded PDF)' }),
      }
    }

    const buffer = Buffer.from(body.fileData, 'base64')
    const { text } = await pdfParse(buffer)
    const result = parseSection(text, body.fileName ?? 'document.pdf')

    return { statusCode: 200, headers: CORS_HEADERS, body: JSON.stringify(result) }
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error'
    return { statusCode: 422, headers: CORS_HEADERS, body: JSON.stringify({ error: message }) }
  }
}
